#!/usr/bin/env node

(function () {
	'use strict';

	var connect = require ('connect');
	var serve = require ('serve-static');

	var port;

	port = process.argv [2];

	console.log ('Starting server at port ' + port + '...');

	connect ().use (serve (__dirname + '/public/')).listen (port);
} ());
